### ISSUE TITLE
Segment-Filter "include" "exclude" Webinar shown as "in" & "!in"

### ISSUE THREAD

**Issue by oltmanns-leuchtfeuer** [Leuchtfeuer/mautic-goto-bundle#13]
Just as title states, currently all the Segment filter for Webinars (attended, registered, did not attend) have an issue with the "including" "excluding" operators. Since the last release I suppose they are shown as "in" for include and "!in" for exclude.

![image](https://user-images.githubusercontent.com/55587275/161936161-3bf6421e-63ca-4a62-9323-a788a405fa70.png)

**Comment by MadlenF** [comment]
Was fixed with https://github.com/Leuchtfeuer/mautic-goto-bundle/pull/39
