### ISSUE TITLE
Not working with Mautic 5

### ISSUE THREAD

**Issue by gabepri** [Leuchtfeuer/mautic-goto-bundle#44]
I previously used the bundled Citrix plugin in Mautic 4.  I did not upgrade to any version of Mautic 4 that was missing the old Citrix plugin.  When I upgraded to Mautic 5, I followed the installation instructions exactly but it appears to be failing silently.  I had no issues with the installation and the cron job doesn't throw any errors.

I know it's not working because I don't see any of the options to use GoToWebinar in my forms or campaigns.

When I go to my plugins directory, I do see this but there are no various "GoTo" cards as the instructions indicate:
![image](https://github.com/Leuchtfeuer/mautic-goto-bundle/assets/73728034/05e3efcf-9986-429a-94d4-e9c6415cfd1c)

I tried removing and recreating the symlink in the instructions but that made no difference.  While the symlink was missing, it functioned exactly the same as when it was there...

**Comment by gabepri** [comment]
@shinde-rahul any thoughts on this?

**Comment by MadlenF** [comment]
Hi @gabepri we have the plugin working with Mautic 5.0.4. 
You do not only need to update your Mautic, but also install the updated version of the plugin. You need to make sure to checkout from the correct branch/[release](https://github.com/Leuchtfeuer/mautic-goto-bundle/releases/tag/4.0.0). The symlink is not needed anymore in Mautic 5.

**Comment by gabepri** [comment]
@MadlenF That is exactly what I had tried and I can confirm it is not working.  To verify, I just re-downloaded the plugin and it is still not working with Mautic 5.

The same comments I put into my initial post are still accurate as to how I know it's not working.  Any other thoughts as to how to fix it?

**Comment by MadlenF** [comment]
Hi @gabepri from your screenshot it looks like maybe the config can not be loaded. This can happen sometimes after re-installing any plugin (e.g. when versions have changed). Please check your database tables `plugins` and `plugin_integrations_setting` if there are any legacy entries and remove them.
