### ISSUE TITLE
Goto Webinar Registration fails with HTTP Code 400 Bad Request if the Organisation Field includes a Pipe Char

### ISSUE THREAD

**Issue by sebastian-fahrenkrog** [Leuchtfeuer/mautic-goto-bundle#46]
The Goto Webinar Registration fails with HTTP Code 400 Bad Request if the Organisation Field includes a Pipe Char.

See also discussion in:
https://community.logmein.com/t5/GoToWebinar-Discussions/Pipe-character-in-field-organization-breaks-registrants-REST-API/td-p/253044

See Pull Request: 
https://github.com/Leuchtfeuer/mautic-goto-bundle/pull/45

**Comment by oltmanns-leuchtfeuer** [comment]
Fixed by PR. :)
